name: CI

on:
  pull_request:
    branches: main
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  unit_tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3.3.0

      - name: "Set up JDK 11"
        uses: actions/setup-java@v3.10.0
        with:
          distribution: zulu
          java-version: 11

      - name: "Lint project"
        run: "support/scripts/lint"

      - name: "Set up Gradle cache"
        uses: gradle/gradle-build-action@v2.3.3

      - name: "Build and run unit tests"
        run: "support/scripts/unit-test"

      - name: "Upload unit test results"
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: unit-test-results
          path: |
            **/build/reports/**/*

  instrumented_tests:
    name: "Instrumented Tests"
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [28]
    timeout-minutes: 60

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3.3.0

      - name: "Set up JDK 11"
        uses: actions/setup-java@v3.10.0
        with:
          distribution: zulu
          java-version: 11

      - name: "Set up Gradle cache"
        uses: gradle/gradle-build-action@v2.3.3

      - name: "Build and run instrumented tests"
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -timezone Australia/Melbourne -camera-back none
          disable-animations: true
          disable-spellchecker: true
          profile: Nexus 5
          arch: x86_64
          ram-size: 4096M
          heap-size: 512M
          script: "support/scripts/instrumented-test"

      - name: "Upload instrumented test results"
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: instrumented-test-results
          path: |
            **/build/reports/*
            **/build/outputs/*/connected/*
