name: CD

on:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test_and_build:
    name: "Run tests and build"
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [28]
    timeout-minutes: 60

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3.3.0

      - name: "Set up JDK 11"
        uses: actions/setup-java@v3.10.0
        with:
          distribution: zulu
          java-version: 11

      - name: "Set up Gradle cache"
        uses: gradle/gradle-build-action@v2.3.3

      - name: "Build and run unit tests"
        run: "support/scripts/unit-test"

      - name: "Upload unit test results"
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: unit-test-results
          path: |
            **/build/reports/**/*

      - name: "Build and run instrumented tests"
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -timezone Australia/Melbourne -camera-back none
          disable-animations: true
          disable-spellchecker: true
          profile: Nexus 5
          arch: x86_64
          ram-size: 4096M
          heap-size: 512M
          script: "support/scripts/instrumented-test"

      - name: "Upload instrumented test results"
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: instrumented-test-results
          path: |
            **/build/reports/*
            **/build/outputs/*/connected/*

      - name: "Create Keystore"
        run: 'echo "${{ secrets.IBA_GOOGLEPLAY_KEYSTORE }}" | base64 -d > ./keystore.jks'

      - name: "Build App Bundle"
        env:
          KEYSTORE_PASSWORD: ${{ secrets.IBA_GOOGLEPLAY_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.IBA_GOOGLEPLAY_KEYSTORE_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.IBA_GOOGLEPLAY_KEYSTORE_KEY_PASSWORD }}
          VERSION_CODE: ${{ github.run_number }}
          VERSION_NAME: ${{ github.run_number }}
          CONFIGURATION: Release
        run: "support/scripts/bundle"

      - name: "Upload app bundle"
        uses: actions/upload-artifact@v3.1.2
        with:
          name: app-bundle
          path: |
            app/build/outputs/bundle/release/app-release.aab
            app/build/outputs/mapping/release/mapping.txt
          retention-days: 1

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: test_and_build
    timeout-minutes: 10

    steps:
      - name: "Download app bundle"
        uses: actions/download-artifact@v3.0.2
        with:
          name: app-bundle

      - name: "Upload bundle to Play Store"
        uses: r0adkll/upload-google-play@v1.1.1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLEPLAY_SERVICE_ACCOUNT }}
          packageName: com.ittybittyapps.apptemplate
          releaseFiles: bundle/release/app-release.aab
          track: internal
          status: draft
