name: Shell Check

on:
  pull_request:
    paths:
      - '.github/workflows/shellcheck.yml'
      - 'support/scripts/**'

jobs:
  shellcheck:
    name: "Shell Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: ShellCheck Support Scripts
        uses: reviewdog/action-shellcheck@v1.17.0
        with:
          reporter: github-pr-review
          path: "support/scripts"
          pattern: "[A-Z]*"
          fail_on_error: true
          filter_mode: file
